name: ai_decision_workshop

channels:
  - conda-forge
dependencies:
  - python=3.11
  - arviz
  - graphviz
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pydot
  - pymc
  - scipy
  - pip
  - pip:
    - git+https://github.com/arviz-devs/preliz.git
