[project]
authors = ["Allen Downey <allen.downey@pymc-labs.com>", 
            "Chris Fonnesbeck <chris.fonnesbeck@pymc-labs.com>"]
channels = ["conda-forge"]
name = "bayesian-decision-workshop"
platforms = ["linux-64", "osx-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
pymc = ">=5.25.1,<6"
pytensor = ">=2.31.7,<3"
arviz = ">=0.22.0,<0.23"
pydot = ">=4.0.1,<5"
pandas = ">=2.3.1,<3"
scipy = ">=1.16.0,<2"
ipykernel = ">=6.30.0,<7"
preliz = ">=0.20.0,<0.21"
ipywidgets = ">=8.1.7,<9"
