[project]
authors = ["Allen Downey <allen.downey@pymc-labs.com>", 
            "Chris Fonnesbeck <chris.fonnesbeck@pymc-labs.com>"]
channels = ["conda-forge"]
name = "bayesian-decision-workshop"
platforms = ["linux-64", "osx-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
jupyter = "*"
pydot = ">=4.0.1,<5"

[pypi-dependencies]
arviz = "*"
graphviz = "*"
matplotlib = "*"
numpy = "*"
pandas = "*"
preliz = {git = "https://github.com/arviz-devs/preliz.git"}
pymc = "*"
scipy = "*"
